#!/bin/bash
# Toggle touchpad. Requires xf86-input-synaptics.
if (synclient | grep TouchpadOff.*1 && synclient TouchpadOff=0); then
(synclient | grep TouchpadOff.*1 && synclient TouchpadOff=0)>/dev/null && echo "TouchPad reactivated." && exit
synclient TouchpadOff=1 && echo "TouchPad deactivated."
else
#Disabling is on default TO DO ABILITATE TOGGLING !!!!
xinput disable $(echo "*$(xinput list --name-only | grep -i touchpad)*" | sed s/^\*/\'/g | sed s/\*$/\'/g )
fi
